### ISSUE TITLE
Is it possible to use this with CachedNetworkImage so we can reduce network calls?

### ISSUE THREAD

**Issue by mark8044** [karan413255/image_stack#7]
Is it possible to use this with CachedNetworkImage so we can reduce network calls?

https://github.com/Baseflow/flutter_cached_network_image

**Comment by pishguy** [comment]
@mark8044 

in `sample` code:

```dart
    List<ImageProvider> providers = [
      ...images.map<ImageProvider>((img) => NetworkImage(
            img,
          ))
    ];
```

you can use `CachedNetworkImage` instead of `NetworkImage`

**Comment by karan413255** [comment]
@mark8044 You can use `ImageStack.widgets()` constructor to pass custom widgets from your app. In that you can pass the widgets wrapped in `CachedNetworkImage`
